### ISSUE TITLE
5.0 Gacha Changes

### ISSUE THREAD

**Issue by EffortlessFury** [Silvoid/GenshinWishProbCalculator#1]
Character pulls now have a second chance for success at the Rate Up 5*, and the Weapon banner only requires a single Fate Point. 

I'll look into making these changes myself and submitting a PR.

**Comment by EffortlessFury** [comment]
There's an assumption I'm not sure I understand in here. The default maximum for weapon pulls is 77 * 3, but isn't the maximum for weapon pulls 80, not 77?

**Comment by Silvoid** [comment]
That assumption comes from this source, https://www.hoyolab.com/article/497840. With where the pity starts and with how much the chance is increased per pull, the weapon banner apparently reaches a 100% chance at 77 pulls for a 5-star.

**Comment by EffortlessFury** [comment]
That is fascinating. Makes sense, though, I suppose, given how the escalation is designed. Alrighty then, I'll look at this soon, unless you want to?

**Comment by Silvoid** [comment]
I'm updating it.

**Comment by Silvoid** [comment]
I pushed it to 5.0 mechanics just now. Later, I will also be pushing the new pre-calculator code to the related repository (the one for what does the pre-calculated data).
